/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 143
#define YY_END_OF_BUFFER 144
static yyconst short int yy_accept[554] =
    {   0,
        0,    0,  144,  143,   50,   49,   47,    1,    3,    4,
      143,    6,    7,    8,   13,   16,   17,   20,   21,   24,
       26,   27,   30,   32,   35,   23,   36,   22,   37,    9,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
       38,   10,   39,   12,   48,    2,    5,    0,   14,   15,
       18,   19,   25,   28,   29,   31,   33,   34,    0,    0,
        0,   43,    0,    0,   45,    0,    0,    0,    0,    0,
        0,    0,    0,   66,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   88,    0,    0,   94,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   11,  142,    0,    0,
       42,   44,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   65,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   80,    0,    0,    0,
        0,   91,    0,    0,    0,    0,   99,  100,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  123,  124,
        0,    0,    0,    0,    0,  130,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   59,    0,    0,   63,    0,   67,
       68,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       86,    0,    0,    0,    0,    0,   95,   96,    0,    0,
      101,    0,    0,  104,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  114,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  127,    0,  129,    0,    0,    0,
        0,    0,  136,    0,    0,    0,    0,    0,  139,   46,
       51,    0,   53,    0,    0,    0,   57,    0,    0,    0,
        0,    0,    0,    0,    0,   72,   73,    0,   79,    0,

        0,   87,    0,    0,   92,    0,   97,   98,    0,    0,
        0,  106,  107,  108,    0,  110,    0,    0,    0,    0,
      116,    0,    0,    0,    0,    0,    0,  125,    0,  128,
        0,    0,    0,    0,    0,  137,  138,    0,    0,    0,
        0,    0,   54,    0,    0,    0,    0,    0,    0,    0,
        0,   70,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  113,
        0,  117,    0,  119,  120,    0,  122,  126,    0,    0,
        0,    0,    0,  141,    0,   41,    0,    0,    0,    0,
        0,   60,    0,    0,   64,    0,   71,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,  102,    0,    0,
        0,  111,    0,    0,  118,  121,    0,    0,    0,    0,
        0,   40,    0,    0,    0,   56,    0,   61,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  131,  132,    0,    0,    0,
        0,    0,   55,    0,    0,    0,   74,   75,   85,    0,
        0,    0,    0,    0,    0,   93,  103,    0,    0,  112,
        0,  133,    0,    0,  140,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   89,    0,    0,    0,    0,    0,
        0,    0,    0,   62,    0,   76,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   58,   69,   77,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       52,   78,   81,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  105,    0,  115,    0,
      135,   82,    0,    0,    0,  109,    0,    0,   84,   90,
      134,   83,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    6,    1,    1,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,    1,
        1,   19,    1,   20,    1,    1,    1,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,    1,   31,   32,
        1,   33,    1,    1,    1,   34,    1,   35,   36,   37,
        1,   38,   39,   40,   41,    1,    1,    1,    1,    1,
       42,   43,   44,   45,   46,    1,   47,   48,   49,   50,

       51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
       61,   62,    1,   63,   64,   65,   66,   67,   68,   69,
       70,    1,   71,   72,   73,   74,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[76] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[554] =
    {   0,
        0,    0,  573,  574,  574,  574,  574,  548,  574,  564,
      495,  574,  574,  574,   64,  574,   63,  574,  574,  548,
      574,   55,  544,   56,  574,  574,  574,  574,  574,  574,
       34,   20,   39,   56,   46,   61,  504,   66,  505,  510,
       59,   44,   65,   82,  513,   70,   69,  501,   90,   30,
      574,  490,  574,  574,  574,  574,  574,  553,  574,  574,
      574,  574,  574,  574,  574,  574,  574,  574,  496,  489,
      509,  574,  504,  505,  492,  489,  506,   92,   80,  491,
      486,   91,   25,  574,  495,  485,  497,   87,  489,   49,
      480,  482,  483,  482,  574,  480,   89,  574,  486,  483,

      470,  478,  487,   88,  109,  478,  470,  484,  468,  466,
      467,   89,  482,  111,  101,  114,  101,  474,  107,   99,
      464,  477,  468,  470,  116,  464,  574,  574,  458,  457,
      574,  574,  474,  469,  470,  458,  453,  465,  450,  454,
      449,  461,  464,  459,  460,  446,  574,  442,  455,  445,
      440,  452,  438,  454,  436,  435,  131,  439,  431,  438,
      444,  148,  434,  442,  431,  430,  574,  574,  425,  438,
      457,  429,  431,  434,  433,  419,  418,  115,  416,  422,
      421,  427,  118,  426,  425,  408,  409,  408,  574,  574,
      421,  406,  406,  408,  417,  574,  157,  420,  411,  415,

      401,  405,  412,  398,  390,  402,  406,  403,  403,  391,
      394,  136,  388,  388,  574,  385,  135,  574,  392,  574,
      574,  384,  383,  387,  395,  387,  379,  389,  380,  390,
      574,  378,  388,  375,  418,  373,  574,  574,  383,  382,
      574,  368,  363,  574,  372,  367,  366,  377,  372,  361,
      378,  373,  368,  574,  375,  351,  357,  356,  369,  366,
      361,  360,  351,  364,  574,  344,  574,  363,  359,  348,
      343,  357,  574,  355,  354,  343,  356,  340,  339,  574,
      574,  349,  574,  334,  343,  337,  574,  366,  337,  347,
      342,  345,  358,  326,  339,  574,  574,  157,  574,  338,

      167,  574,  328,  321,  574,  333,  574,  574,  335,  328,
      327,  574,  574,  574,  322,  574,  315,  330,  329,  312,
      574,  316,  311,  309,  310,  312,  322,  574,  316,  574,
      308,  315,  308,  315,  325,  574,  574,  296,  314,  311,
      300,  330,  574,  299,  292,  296,  291,  290,  308,  283,
      305,  574,  287,  303,  289,  301,  292,  295,  287,  293,
      292,  296,  294,  286,  275,  274,  282,  285,  270,  574,
      287,  574,  282,  574,  574,  279,  574,  574,  268,  275,
      270,  282,  272,  574,  261,  574,  270,  263,  272,  271,
      262,  574,  269,  267,  574,  258,  574,  253,  258,  250,

      249,  249,  265,  253,  250,  246,  259,  574,  242,  241,
      241,  574,  253,  255,  574,  574,  237,  241,  245,  236,
      239,  574,  237,  237,  232,  574,  232,  574,  230,  242,
      226,  220,  238,  237,  222,  237,  234,  219,  232,  231,
      217,  225,  214,  228,  219,  574,  574,  211,  224,  223,
      208,  210,  574,  224,  209,  211,  574,  250,  574,  204,
      215,  214,  215,  199,  213,  574,  574,  212,  205,  574,
      208,  574,  209,  218,  574,  209,  195,  195,  202,  235,
      204,  200,  195,  183,  574,  186,  212,  196,  206,  182,
      177,  181,  170,  574,  176,  221,  179,  202,  174,  198,

      170,  171,  197,  179,  166,  181,  157,  574,  574,  209,
      161,  163,  165,  159,  171,  171,  158,  171,  167,  151,
      574,  574,  574,  154,  164,  163,  148,  154,  161,  159,
      144,  156,  143,  152,  147,  146,  574,  139,  574,  144,
      574,  574,  131,  129,  125,  574,  114,   27,  574,  574,
      574,  574,  574
    } ;

static yyconst short int yy_def[554] =
    {   0,
      553,    1,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,

      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,

      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,

      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,

      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,

      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,    0
    } ;

static yyconst short int yy_nxt[650] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,    4,    4,    4,    4,
       20,   21,   22,   23,   24,   25,   26,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,   27,   28,   29,   30,    4,   31,   32,   33,   34,
       35,   36,   37,    4,   38,   39,    4,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,    4,    4,
       51,   52,   53,   54,   55,   59,   61,   64,   65,   67,
       68,   69,   74,  125,  126,   76,   62,   60,  146,   75,
      552,  147,   77,   70,  104,   85,   78,   71,   72,   79,

       73,   80,   81,   86,  105,  101,   82,   89,  154,  106,
       83,  155,   87,  102,   88,   90,   84,   95,   91,  103,
      115,   92,  119,   93,   96,   97,  107,  108,  110,   98,
      109,  120,  111,  121,  116,  117,  123,  118,  137,  139,
      170,  151,  143,  178,  112,  140,  138,  113,  144,  179,
      124,  152,  161,  162,  145,  168,  169,  181,  185,  190,
      188,  193,  191,  186,  195,  187,  201,  235,  196,  194,
      202,  229,  182,  171,  250,  183,  189,  184,  551,  230,
      256,  251,  285,  257,  268,  269,  270,  290,  354,  550,
      286,  549,  355,  548,  547,  546,  545,  544,  236,  291,

      357,  358,  543,  359,  542,  360,  541,  540,  539,  538,
      537,  536,  535,  534,  533,  532,  531,  530,  529,  528,
      527,  526,  525,  524,  523,  522,  521,  520,  519,  518,
      517,  516,  515,  514,  513,  512,  511,  510,  509,  508,
      507,  506,  505,  504,  503,  502,  501,  500,  499,  498,
      497,  496,  495,  494,  493,  492,  491,  490,  489,  488,
      487,  486,  485,  484,  483,  482,  481,  480,  479,  478,
      477,  476,  475,  474,  473,  472,  471,  470,  469,  468,
      467,  466,  465,  464,  463,  462,  461,  460,  459,  458,
      457,  456,  455,  454,  453,  452,  451,  450,  449,  448,

      447,  446,  445,  444,  443,  442,  441,  440,  439,  438,
      437,  436,  435,  434,  433,  432,  431,  430,  429,  428,
      427,  426,  425,  424,  423,  422,  421,  420,  419,  418,
      417,  416,  415,  414,  413,  412,  411,  410,  409,  408,
      407,  406,  405,  404,  403,  402,  401,  400,  399,  398,
      397,  396,  395,  394,  393,  392,  391,  390,  389,  388,
      387,  386,  385,  384,  383,  382,  381,  380,  379,  378,
      377,  376,  375,  374,  373,  372,  371,  370,  369,  368,
      367,  366,  365,  364,  363,  362,  361,  356,  353,  352,
      351,  350,  349,  348,  347,  346,  345,  344,  343,  342,

      341,  340,  339,  338,  337,  336,  335,  334,  333,  332,
      331,  330,  329,  328,  327,  326,  325,  324,  323,  322,
      321,  320,  319,  318,  317,  316,  315,  314,  313,  312,
      311,  310,  309,  308,  307,  306,  305,  304,  303,  302,
      301,  300,  299,  298,  297,  296,  295,  294,  293,  292,
      289,  288,  287,  284,  283,  282,  281,  280,  279,  278,
      277,  276,  275,  274,  273,  272,  271,  267,  266,  265,
      264,  263,  262,  261,  260,  259,  258,  255,  254,  253,
      252,  249,  248,  247,  246,  245,  244,  243,  242,  241,
      240,  239,  238,  237,  234,  233,  232,  231,  228,  227,

      226,  225,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  203,  200,  199,  198,  197,  192,  180,
      177,  176,  175,  174,  173,  172,  167,  166,  165,  164,
      163,  160,  159,  158,  157,  156,  153,  150,  149,  148,
      142,  141,  136,  135,  134,  133,  132,  131,  130,  129,
      128,  127,  122,  114,  100,   99,   94,   66,   63,   58,
       57,   56,  553,    3,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,

      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553
    } ;

static yyconst short int yy_chk[650] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   15,   17,   22,   22,   24,
       24,   31,   32,   50,   50,   33,   17,   15,   83,   32,
      548,   83,   33,   31,   42,   35,   33,   31,   31,   33,

       31,   33,   34,   35,   42,   41,   34,   36,   90,   42,
       34,   90,   35,   41,   35,   36,   34,   38,   36,   41,
       46,   36,   47,   36,   38,   38,   43,   43,   44,   38,
       43,   47,   44,   47,   46,   46,   49,   46,   78,   79,
      105,   88,   82,  112,   44,   79,   78,   44,   82,  112,
       49,   88,   97,   97,   82,  104,  104,  114,  115,  117,
      116,  119,  117,  115,  120,  115,  125,  162,  120,  119,
      125,  157,  114,  105,  178,  114,  116,  114,  547,  157,
      183,  178,  212,  183,  197,  197,  197,  217,  298,  545,
      212,  544,  298,  543,  540,  538,  536,  535,  162,  217,

      301,  301,  534,  301,  533,  301,  532,  531,  530,  529,
      528,  527,  526,  525,  524,  520,  519,  518,  517,  516,
      515,  514,  513,  512,  511,  510,  507,  506,  505,  504,
      503,  502,  501,  500,  499,  498,  497,  496,  495,  493,
      492,  491,  490,  489,  488,  487,  486,  484,  483,  482,
      481,  480,  479,  478,  477,  476,  474,  473,  471,  469,
      468,  465,  464,  463,  462,  461,  460,  458,  456,  455,
      454,  452,  451,  450,  449,  448,  445,  444,  443,  442,
      441,  440,  439,  438,  437,  436,  435,  434,  433,  432,
      431,  430,  429,  427,  425,  424,  423,  421,  420,  419,

      418,  417,  414,  413,  411,  410,  409,  407,  406,  405,
      404,  403,  402,  401,  400,  399,  398,  396,  394,  393,
      391,  390,  389,  388,  387,  385,  383,  382,  381,  380,
      379,  376,  373,  371,  369,  368,  367,  366,  365,  364,
      363,  362,  361,  360,  359,  358,  357,  356,  355,  354,
      353,  351,  350,  349,  348,  347,  346,  345,  344,  342,
      341,  340,  339,  338,  335,  334,  333,  332,  331,  329,
      327,  326,  325,  324,  323,  322,  320,  319,  318,  317,
      315,  311,  310,  309,  306,  304,  303,  300,  295,  294,
      293,  292,  291,  290,  289,  288,  286,  285,  284,  282,

      279,  278,  277,  276,  275,  274,  272,  271,  270,  269,
      268,  266,  264,  263,  262,  261,  260,  259,  258,  257,
      256,  255,  253,  252,  251,  250,  249,  248,  247,  246,
      245,  243,  242,  240,  239,  236,  235,  234,  233,  232,
      230,  229,  228,  227,  226,  225,  224,  223,  222,  219,
      216,  214,  213,  211,  210,  209,  208,  207,  206,  205,
      204,  203,  202,  201,  200,  199,  198,  195,  194,  193,
      192,  191,  188,  187,  186,  185,  184,  182,  181,  180,
      179,  177,  176,  175,  174,  173,  172,  171,  170,  169,
      166,  165,  164,  163,  161,  160,  159,  158,  156,  155,

      154,  153,  152,  151,  150,  149,  148,  146,  145,  144,
      143,  142,  141,  140,  139,  138,  137,  136,  135,  134,
      133,  130,  129,  126,  124,  123,  122,  121,  118,  113,
      111,  110,  109,  108,  107,  106,  103,  102,  101,  100,
       99,   96,   94,   93,   92,   91,   89,   87,   86,   85,
       81,   80,   77,   76,   75,   74,   73,   71,   70,   69,
       58,   52,   48,   45,   40,   39,   37,   23,   20,   11,
       10,    8,    3,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,

      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "l.lt"
#define INITIAL 0
#line 2 "l.lt"

#include "XPPLanguageTypesEnum.h"

#line 694 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 10 "l.lt"



#line 849 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 554 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 574 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 13 "l.lt"
return RelationNot;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 14 "l.lt"
return RelationNotEqual;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 15 "l.lt"
return PrefixMacro;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 16 "l.lt"
return BynaryAnd;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 17 "l.lt"
return LogicalAnd;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 18 "l.lt"
return LeftBracket;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 19 "l.lt"
return RightBracket;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 20 "l.lt"
return MULT;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 21 "l.lt"
return BYNARYXOR;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 22 "l.lt"
return BYNARYOR;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 23 "l.lt"
return LOGICALOR;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 24 "l.lt"
return ARITMETICNOT;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 25 "l.lt"
return PLUS;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 26 "l.lt"
return INCREMENT;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 27 "l.lt"
return ADDITIVEASSIGNMENT;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 28 "l.lt"
return COMMA;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 29 "l.lt"
return MINUS;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 30 "l.lt"
return DECREMENT;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 31 "l.lt"
return SUBSTRACTIVEASSIGNMENT;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 32 "l.lt"
return DOT;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 33 "l.lt"
return DEVICE;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 34 "l.lt"
XPPLanguageTypes: ESCAPE;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 35 "l.lt"
return ESCAPEOFKEYWORD;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 36 "l.lt"
return colons;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 37 "l.lt"
return DOUBLEcolons;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 38 "l.lt"
return SEMICOLLUMN;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 39 "l.lt"
return LESSTHAN;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 40 "l.lt"
return ShiftleftOperator;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 41 "l.lt"
return LESSTHANOREQUAL;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 42 "l.lt"
return ASSIGNOPERATOR;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 43 "l.lt"
return EQUALCHECK;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 44 "l.lt"
return GREATERTHAN;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 45 "l.lt"
return GREATERTHANOREQUAL;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 46 "l.lt"
return ShiftRightOperator;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 47 "l.lt"
return TernalOperator;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 48 "l.lt"
return LeftSquareBrackets;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 49 "l.lt"
return RightSquareBrackets;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 50 "l.lt"
return LeftCurlyBrackets;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 51 "l.lt"
return RightCurlyBrackets;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 52 "l.lt"
return ABSTRACT;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 53 "l.lt"
return ANYTYPE;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 54 "l.lt"
return ASC;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 55 "l.lt"
return AT;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 56 "l.lt"
return AVG;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 57 "l.lt"
return BY;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 58 "l.lt"
return BYREF;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 59 "l.lt"
return SPACE ;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 60 "l.lt"
return EOF1 ;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 61 "l.lt"
return NEWLINE ;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 62 "l.lt"
return TAB ;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 63 "l.lt"
return CATCH;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 64 "l.lt"
return CHANGECOMPANY;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 65 "l.lt"
return CLASS;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 66 "l.lt"
return CLIENT;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 67 "l.lt"
return CONTAINER;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 68 "l.lt"
return CONTINUE;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 69 "l.lt"
return COUNT;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 70 "l.lt"
return CROSSCOMPANY;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 71 "l.lt"
return DATE;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 72 "l.lt"
return DEFAULT;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 73 "l.lt"
return DELEGATE;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 74 "l.lt"
return DELETE_FROM;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 75 "l.lt"
return DESC;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 76 "l.lt"
return DISPLAY;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 77 "l.lt"
return DIV;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 78 "l.lt"
return DO;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 79 "l.lt"
return EDIT;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 80 "l.lt"
return ELSE;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 81 "l.lt"
return EVENTHANDLER;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 82 "l.lt"
return EXISTS;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 83 "l.lt"
return EXTENDS;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 84 "l.lt"
return FALSE;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 85 "l.lt"
return FINAL;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 86 "l.lt"
return FIRSTFAST;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 87 "l.lt"
return FIRSTONLY;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 88 "l.lt"
return FIRSTONLY10;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 89 "l.lt"
return FIRSTONLY100;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 90 "l.lt"
return FIRSTONLY1000;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 91 "l.lt"
return FLUSH;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 92 "l.lt"
return FOR;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 93 "l.lt"
return FORCELITEREALS;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 94 "l.lt"
return FORCENESTEDLOOP;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 95 "l.lt"
return FORCEPLACEHOLDERS;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 96 "l.lt"
return FORCESELECTORDER;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 97 "l.lt"
return FORUPDATE;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 98 "l.lt"
return FROM;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 99 "l.lt"
return GROUP;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 100 "l.lt"
return IF;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 101 "l.lt"
return IMPLEMENTS;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 102 "l.lt"
return INSERT_RECORDSET;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 103 "l.lt"
return INT;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 104 "l.lt"
return INT64;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 105 "l.lt"
return INTERFACE;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 106 "l.lt"
return IS;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 107 "l.lt"
return JOIN;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 108 "l.lt"
return LIKE;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 109 "l.lt"
return MAXOF;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 110 "l.lt"
return MINOF;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 111 "l.lt"
return MOD;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 112 "l.lt"
return NEW;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 113 "l.lt"
return NEXT;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 114 "l.lt"
return NOFETCH;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 115 "l.lt"
return NOTEXISTS;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 116 "l.lt"
return NULL1;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 117 "l.lt"
return OPTIMISTICLOCK;
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 118 "l.lt"
return ORDER;
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 119 "l.lt"
return OUTER;
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 120 "l.lt"
return PAUSE;
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 121 "l.lt"
return PESSIMISTICLOCK;
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 122 "l.lt"
return PRINT;
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 123 "l.lt"
return PRIVATE;
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 124 "l.lt"
return PROTECTED;
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 125 "l.lt"
return PUBLIC;
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 126 "l.lt"
return REAL;
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 127 "l.lt"
return REAPEATABLEREAD;
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 128 "l.lt"
return RETRY;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 129 "l.lt"
return RETURN;
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 130 "l.lt"
return REVERSE;
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 131 "l.lt"
return SELECT;
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 132 "l.lt"
return SERVER;
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 133 "l.lt"
return SETTING;
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 134 "l.lt"
return STATIC;
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 135 "l.lt"
return STR;
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 136 "l.lt"
return SUM;
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 137 "l.lt"
return SUPER;
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 138 "l.lt"
return SWITCH;
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 139 "l.lt"
return THIS;
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 140 "l.lt"
return THROW;
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 141 "l.lt"
return TRUE;
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 142 "l.lt"
return TRY;
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 143 "l.lt"
return TTSABORT;
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 144 "l.lt"
return TTSBEGIN;
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 145 "l.lt"
return TTSCOMMIT;
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 146 "l.lt"
return UPDATE_RECORDSET;
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 147 "l.lt"
return VALIDTIMESTATE;
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 148 "l.lt"
return VOID;
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 149 "l.lt"
return WHERE;
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 150 "l.lt"
return WHILE; 
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 151 "l.lt"
return BREAK;
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 152 "l.lt"
return BREAKPOINT;
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 153 "l.lt"
return WINDOW;
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 154 "l.lt"
return EOF1;
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 156 "l.lt"
ECHO;
	YY_BREAK
#line 1647 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 75);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 554 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 75;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 554 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 553);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 156 "l.lt"


int yywrap()
{
    return 1;
}

